# Generated by Django 3.2.7 on 2021-10-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='label')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start_time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end_time')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is_completed')),
                ('employee', models.ManyToManyField(related_name='work', to='users.Employee')),
                ('label', models.ManyToManyField(blank=True, null=True, related_name='work', to='work_api.Label')),
            ],
        ),
    ]
