# Generated by Django 3.2.7 on 2021-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_api', '0002_alter_work_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='label',
            field=models.ManyToManyField(blank=True, to='work_api.Label'),
        ),
    ]
