# Generated by Django 3.2.7 on 2021-10-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_api', '0003_alter_work_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='employee',
            new_name='employees',
        ),
    ]
